package install

import (
	"crypto/sha256"
	"fmt"
	"strings"
	"testing"
)

func TestParseChecksums(t *testing.T) {
	body := `
# generated by release packaging
2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824  aidlc_darwin_x86_64.tar.gz
486ea46224d1bb4fb680f34f7c9ad96a8f24ec88be73ea8e5a6c65260e9cb8a7 *aidlc_linux_arm64.tar.gz
`

	checksums, err := ParseChecksums(strings.NewReader(body))
	if err != nil {
		t.Fatalf("ParseChecksums() error = %v", err)
	}
	if got := checksums["aidlc_darwin_x86_64.tar.gz"]; got != "2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824" {
		t.Fatalf("darwin checksum = %q", got)
	}
	if got := checksums["aidlc_linux_arm64.tar.gz"]; got != "486ea46224d1bb4fb680f34f7c9ad96a8f24ec88be73ea8e5a6c65260e9cb8a7" {
		t.Fatalf("linux checksum = %q", got)
	}
}

func TestParseChecksumsRejectsUnsafeNames(t *testing.T) {
	_, err := ParseChecksums(strings.NewReader("2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824  ../aidlc.tar.gz\n"))
	if err == nil {
		t.Fatal("ParseChecksums() error = nil")
	}
}

func TestVerifyChecksum(t *testing.T) {
	sum := sha256.Sum256([]byte("artifact"))
	checksums := ChecksumSet{"aidlc.tar.gz": fmt.Sprintf("%x", sum)}

	if err := VerifyChecksum(strings.NewReader("artifact"), "aidlc.tar.gz", checksums); err != nil {
		t.Fatalf("VerifyChecksum() error = %v", err)
	}
}

func TestVerifyChecksumMismatch(t *testing.T) {
	sum := sha256.Sum256([]byte("artifact"))
	checksums := ChecksumSet{"aidlc.tar.gz": fmt.Sprintf("%x", sum)}

	err := VerifyChecksum(strings.NewReader("modified"), "aidlc.tar.gz", checksums)
	if err == nil {
		t.Fatal("VerifyChecksum() error = nil")
	}
}
