package contract

import "fmt"

// IDE identifies a supported editor or agent surface generated by AIDLC.
type IDE string

const (
	IDEClaude   IDE = "claude"
	IDECodex    IDE = "codex"
	IDECursor   IDE = "cursor"
	IDECopilot  IDE = "copilot"
	IDEWindsurf IDE = "windsurf"
	IDEAll      IDE = "all"
)

var supportedIDEs = []IDE{
	IDEClaude,
	IDECodex,
	IDECursor,
	IDECopilot,
	IDEWindsurf,
	IDEAll,
}

var concreteIDEs = []IDE{
	IDEClaude,
	IDECodex,
	IDECursor,
	IDECopilot,
	IDEWindsurf,
}

func SupportedIDEs() []IDE {
	out := make([]IDE, len(supportedIDEs))
	copy(out, supportedIDEs)
	return out
}

func ConcreteIDEs() []IDE {
	out := make([]IDE, len(concreteIDEs))
	copy(out, concreteIDEs)
	return out
}

func ParseIDE(value string) (IDE, error) {
	ide := IDE(value)
	for _, supported := range supportedIDEs {
		if ide == supported {
			return ide, nil
		}
	}
	return "", fmt.Errorf("unsupported IDE %q", value)
}

func (i IDE) String() string {
	return string(i)
}

func (i IDE) IsAggregate() bool {
	return i == IDEAll
}

func NormalizeIDESelection(values []IDE) ([]IDE, error) {
	selected := make(map[IDE]bool, len(concreteIDEs))
	for _, value := range values {
		if value == "" {
			continue
		}
		ide, err := ParseIDE(value.String())
		if err != nil {
			return nil, err
		}
		if ide.IsAggregate() {
			for _, concrete := range concreteIDEs {
				selected[concrete] = true
			}
			continue
		}
		selected[ide] = true
	}

	out := make([]IDE, 0, len(selected))
	for _, ide := range concreteIDEs {
		if selected[ide] {
			out = append(out, ide)
		}
	}
	return out, nil
}

func MergeIDESelections(left, right []IDE) ([]IDE, error) {
	merged := make([]IDE, 0, len(left)+len(right))
	merged = append(merged, left...)
	merged = append(merged, right...)
	return NormalizeIDESelection(merged)
}
